version: '3'
services:
    web:
        image: nginx:latest
        ports:
            - "8081:80"
            - "443:443"
        volumes:
            - ./www:/var/www/html
            - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./logs/nginx:/var/log/nginx
        links:
            - php
        networks:
        - R_projetA
    php:
        image: php:7-fpm
        ports:
            - "9080:9000"
        volumes:
            - ./www:/var/www/html
            - ./config/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.conf
            - ./config/php-fpm/php:/usr/local/etc/php
        links:
            - mysql
            - redis
        networks:
        - R_projetA
    mysql:
        image: mysql:latest
        ports:
            - "3306:3306"
        volumes:
            - ./.data/db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
        networks:
        - R_projetA
    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        networks:
        - R_projetA
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5
        ports:
          - 8089:80
        environment:
          PMA_HOST: mysql
        links:
            - mysql
networks:
    R_projetA:
      driver: bridge
      ipam:
        driver: default
        config:
        - subnet: 172.19.0.0/16