version: '3.7'
services:
  reverse-proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    networks:
      - R_proxy
networks:
    R_proxy:
      driver: bridge
      ipam:
        config:
        - subnet: 172.18.0.0/16
